# Generated by Django 3.2.4 on 2021-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0004_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, help_text='Donnez les détails de ce que vous cherchez.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Téléversez la couverture du livre (facultatif)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(help_text='Entrez le titre du livre.', max_length=128, verbose_name='Titre'),
        ),
    ]
